# Generated by Django 4.2 on 2023-05-05 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0002_alter_customer_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least 8 characters, with at least one letter, one number, and one special character', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$')]),
        ),
    ]
