# Generated by Django 4.2 on 2023-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0003_alter_registration_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
