# Generated by Django 4.2 on 2023-05-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0007_remove_product_description_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=False, upload_to='productimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
