# Generated by Django 4.2 on 2023-05-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
